[package]
name = "symbios-tensor"
version = "0.4.1"
edition = "2024"
authors = ["Janus"]
description = "A procedural generation engine for urban layouts."
license = "MIT"
readme = "README.md"
repository = "https://github.com/TheJanusStream/symbios-tensor"
keywords = ["procedural", "generative", "simulation"]
categories = ["simulation", "game-development", "mathematics"]

[dependencies]
glam = { version = "0.32", features = ["serde"] }
rand = "0.9"
rand_pcg = "0.9"
symbios-ground = "0.4"
serde = { version = "1.0", features = ["derive", "rc"] }

[dev-dependencies]
serde_json = "1.0"
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "bench_main"
harness = false

[profile.bench]
debug = true
